export const ImagesPath = {
    SplashScreen: require(`../../Assets/superMarket.jpg`),
    loginImage: require(`../../Assets/loginImage.png`),
    Adult: require(`../../Assets/Adult-and-senior-eye-exams-icon.png`),
    eyeImage: require(`../../Assets/eyeImage.png`),
    eyeSlashImage: require(`../../Assets/eyeSlashImage.png`),
    passwordImages: require(`../../Assets/passwordImages.png`),
    emailImages: require(`../../Assets/emailImages.webp`),
    firstName: require(`../../Assets/firstName.png`),
    creditCardNumber: require(`../../Assets/creditCardNumber.png`),
    arrowBack: require(`../../Assets/arrowBack.webp`),
    facebookImages: require(`../../Assets/facebookImages.png`),
    GoogleImages: require(`../../Assets/GoogleImages.png`),
    supermarket2: require(`../../Assets/supermarket2.png`),
    manSuperMarket: require(`../../Assets/manSuperMarket.png`),
    logo: require(`../../Assets/LoginScreenLogo.jpeg`),
    hemberger2: require(`../../Assets/hemberger2.png`),
    cardImage: require(`../../Assets/cardImage.png`),
    cardImage1: require(`../../Assets/cardImage1.png`),
    cardImage2: require(`../../Assets/cardImage2.jpg`),
    cardImage3: require(`../../Assets/cardImage3.png`),
    backIcON: require(`../../Assets/backIcON.png`),
    logoutIcon: require(`../../Assets/logoutIcon.webp`),
    homeBlackImage: require(`../../Assets/homeBlackImage.png`),
    homeWhiteImage: require(`../../Assets/homeWhiteImage.png`),
    Profile: require(`../../Assets/Profile.png`),
    profileBlack: require(`../../Assets/profileBlack.webp`),
    feedbackBlack: require(`../../Assets/feedbackBlack.png`),
    feedbackBlack: require(`../../Assets/feedbackBlack.png`),
    feedbackWhite: require(`../../Assets/feedbackWhite.png`),
    HomeScreenLogo: require (`../../Assets/HomeScreenLogoFinal.jpeg`),
    PhoneIcon: require (`../../Assets/PhoneLogo.jpg`),
    AppleIcon: require (`../../Assets/apple-icon.png`),
    BananaIcon: require (`../../Assets/banana.png`),
    BottleIcon: require ('../../Assets/water-bottle.png'),
}